# Generated by Django 5.2 on 2026-01-28 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('pagos', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], default='email', max_length=20)),
                ('tipo_evento', models.CharField(choices=[('recordatorio_cita', 'Recordatorio de Cita'), ('cita_confirmada', 'Cita Confirmada'), ('cita_cancelada', 'Cita Cancelada'), ('cita_modificada', 'Cita Modificada'), ('compra_confirmada', 'Compra Confirmada'), ('pago_recibido', 'Pago Recibido'), ('producto_disponible', 'Producto Disponible'), ('stock_bajo', 'Stock Bajo'), ('bienvenida', 'Bienvenida'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('asunto', models.CharField(blank=True, max_length=200)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('fallida', 'Fallida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_programada', models.DateTimeField(blank=True, help_text='Fecha programada para envío (null para envío inmediato)', null=True)),
                ('fecha_enviada', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.CharField(help_text='Email, teléfono o token según el canal', max_length=255)),
                ('id_externo', models.CharField(blank=True, help_text='ID de la notificación en el servicio externo (Resend, Twilio, etc.)', max_length=100)),
                ('error', models.TextField(blank=True, help_text='Mensaje de error si falló')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='citas.cita')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='productos.compra')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='pagos.pago')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario destinatario (null para notificaciones globales)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='notificacio_usuario_9d2c05_idx'), models.Index(fields=['canal', 'estado'], name='notificacio_canal_1067ae_idx'), models.Index(fields=['tipo_evento', 'fecha_creacion'], name='notificacio_tipo_ev_1bf7ab_idx'), models.Index(fields=['fecha_programada', 'estado'], name='notificacio_fecha_p_dc270c_idx')],
            },
        ),
    ]
