# Generated by Django 5.2 on 2026-01-28 16:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('id_operacion', models.CharField(blank=True, help_text='ID de operación bancaria', max_length=100)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('mercado_pago_id', models.CharField(blank=True, help_text='ID de preferencia/pago de Mercado Pago', max_length=100)),
                ('mercado_pago_status', models.CharField(blank=True, max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='citas.cita')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_cliente', to=settings.AUTH_USER_MODEL)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='productos.compra')),
                ('validado_por', models.ForeignKey(blank=True, help_text='Secretaria que validó el pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['cliente', 'estado'], name='pagos_pago_cliente_01e94c_idx'), models.Index(fields=['estado', 'metodo_pago'], name='pagos_pago_estado_d218c7_idx'), models.Index(fields=['cita', 'compra'], name='pagos_pago_cita_id_786755_idx')],
            },
        ),
    ]
