# Generated by Django 5.2 on 2026-01-28 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
        ('productos', '0002_ordencompra_ordencompraitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='productos.ordencompra'),
        ),
    ]
