# Generated by Django 5.2 on 2026-01-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], unique=True)),
                ('demanda', models.CharField(choices=[('alta', 'Alta Demanda'), ('media', 'Media Demanda'), ('baja', 'Baja Demanda')], default='media', max_length=10)),
                ('dias_anticipacion_alta', models.IntegerField(default=3, help_text='Días de anticipación para agendar en alta demanda')),
                ('dias_anticipacion_media', models.IntegerField(default=2, help_text='Días de anticipación para agendar en media demanda')),
                ('dias_anticipacion_baja', models.IntegerField(default=1, help_text='Días de anticipación para agendar en baja demanda')),
                ('dias_cancelacion_alta', models.IntegerField(default=2, help_text='Días de anticipación para cancelar en alta demanda')),
                ('dias_cancelacion_media', models.IntegerField(default=1, help_text='Días de anticipación para cancelar en media demanda')),
                ('dias_cancelacion_baja', models.IntegerField(default=1, help_text='Días de anticipación para cancelar en baja demanda')),
                ('tiempo_espera_maximo', models.IntegerField(default=10, help_text='Minutos máximos de espera antes de cancelar automáticamente')),
                ('costo_moto_mandado', models.DecimalField(decimal_places=2, default=40.0, max_digits=10)),
                ('costo_paqueteria', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('porcentaje_anticipo_penalizado', models.DecimalField(decimal_places=2, default=50.0, help_text='Porcentaje de anticipo cuando hay penalización', max_digits=5)),
                ('citas_penalizadas', models.IntegerField(default=10, help_text='Número de citas con anticipo obligatorio después de inasistencia')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'ordering': ['dia_semana'],
            },
        ),
    ]
