# Generated by Django 5.2 on 2025-11-15 18:48

from django.db import migrations, models, connection


def add_totp_enabled_if_not_exists(apps, schema_editor):
    """Agrega el campo totp_enabled solo si no existe en la BD"""
    db_table = 'accounts_usuario'
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            # Verificar si la columna ya existe en PostgreSQL
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name=%s AND column_name='totp_enabled'
            """, [db_table])
            
            if not cursor.fetchone():
                # Si no existe, agregarla
                cursor.execute("""
                    ALTER TABLE accounts_usuario 
                    ADD COLUMN totp_enabled BOOLEAN NOT NULL DEFAULT FALSE
                """)
        # Para SQLite, Django manejará la migración automáticamente


def remove_totp_enabled_if_exists(apps, schema_editor):
    """No hacer nada en rollback para evitar problemas"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_codigo_otp_usuario_confirmado_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_totp_enabled_if_not_exists,
                    reverse_code=remove_totp_enabled_if_exists,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='usuario',
                    name='totp_enabled',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
