# Generated by Django 5.2 on 2025-11-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_codigo_otp_usuario_confirmado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
