# Generated by Django 5.2 on 2026-01-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_configuracionsistema_producto_servicio_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
    ]
