"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-p&f859sfsdb#et935ty(dwxij=$6y$8_yv-l=nqi&$&)(smms_')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,backendbina-1.onrender.com', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # Para Angular frontend
    'accounts',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ✅ Debe estar PRIMERO
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Para archivos estáticos en producción
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
    #'default': {
     #   'ENGINE': 'django.db.backends.sqlite3',
      #  'NAME': BASE_DIR / 'db.sqlite3',
    #}
#}
# Usar PostgreSQL en producción, SQLite en desarrollo

if config('DATABASE_URL', default=None):

    # Producción: PostgreSQL desde Render

    import dj_database_url

    DATABASES = {

        'default': dj_database_url.config(

            default=config('DATABASE_URL'),

            conn_max_age=600,

            conn_health_checks=True,

        )

    }

else:

    # Desarrollo: SQLite

    DATABASES = {

        'default': {

            'ENGINE': 'django.db.backends.sqlite3',

            'NAME': BASE_DIR / 'db.sqlite3',

        }

    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

 

# WhiteNoise para servir archivos estáticos en producción

if not DEBUG:

    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.Usuario'

# Configuración de Email (usando variables de entorno)
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 465
#EMAIL_USE_SSL = True
#EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='joadanvidal@gmail.com')
#EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='pkpukuqtvxbqqkvf')
#DEFAULT_FROM_EMAIL = EMAIL_HOST_USER# Configuración de Email con Resend

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.resend.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'resend'  # Literal "resend", no cambiar
EMAIL_HOST_PASSWORD = config('RESEND_API_KEY', default='')  # Tu API Key de Resend
DEFAULT_FROM_EMAIL = 'onboarding@resend.dev'  # Email por defecto de Resend (gratis)

# Configuración de SendGrid para OTP
SENDGRID_API_KEY = config('SENDGRID_API_KEY', default='')
SENDGRID_FROM_EMAIL = config('SENDGRID_FROM_EMAIL', default='')
SENDGRID_FROM_NAME = config('SENDGRID_FROM_NAME', default='modulo usuario')

# Configuración CORS para Angular Frontend y Vercel
# Obtener URL del frontend desde variables de entorno
FRONTEND_URL = config('FRONTEND_URL', default='https://frontbina.vercel.app')

# Lista de orígenes permitidos (orígenes específicos)
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='https://frontbina.vercel.app,http://localhost:4200,http://127.0.0.1:4200',
    cast=Csv()
)

# Permitir todos los subdominios de Vercel (para preview deployments)
# IMPORTANTE: El regex debe ser una lista de strings (patrones regex)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",  # Permite cualquier subdominio de Vercel
]

# Función personalizada para verificar orígenes (fallback si regex no funciona)
def cors_allow_origin(origin, request):
    """Función personalizada para permitir orígenes de Vercel"""
    if origin:
        # Permitir cualquier subdominio de vercel.app
        if origin.endswith('.vercel.app'):
            return True
        # Permitir localhost para desarrollo
        if origin.startswith('http://localhost:') or origin.startswith('http://127.0.0.1:'):
            return True
    return None  # Dejar que django-cors-headers maneje el resto con CORS_ALLOWED_ORIGINS

# Usar función personalizada como fallback si el regex no funciona
# Esta función tiene prioridad sobre CORS_ALLOWED_ORIGINS y CORS_ALLOWED_ORIGIN_REGEXES
CORS_ALLOW_ORIGIN_FUNC = cors_allow_origin

CORS_ALLOW_CREDENTIALS = True  # Para permitir cookies/sesiones

# Configuración adicional para asegurar que CORS funcione
CORS_PREFLIGHT_MAX_AGE = 86400  # Cache preflight requests por 24 horas

# Headers permitidos
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Métodos permitidos
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
# CSRF Settings para Angular y Vercel
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='https://frontbina.vercel.app,http://localhost:4200,http://127.0.0.1:4200',
    cast=Csv()
)

# Session Settings
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not DEBUG  # True en producción
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 86400  # 24 horas

# CSRF Cookie Settings
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG

CSRF_COOKIE_HTTPONLY = False  # Angular necesita leer el token




