"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No default - fuerza configuración en producción
try:
    SECRET_KEY = config('SECRET_KEY')
    if SECRET_KEY.startswith('django-insecure'):
        raise ValueError('SECRET_KEY insegura detectada')
except Exception:
    if DEBUG:
        SECRET_KEY = 'django-dev-key-ONLY-FOR-DEVELOPMENT'
    else:
        raise Exception('SECRET_KEY must be set in production environment')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,backendbina-1.onrender.com', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # Para Angular frontend
    'rest_framework',  # Django REST Framework
    'axes',  # Django Axes - protección fuerza bruta
    'csp',  # Django CSP - Content Security Policy
    'accounts',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ✅ Debe estar PRIMERO
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Para archivos estáticos en producción
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',  # Django Axes - debe estar después de AuthenticationMiddleware
    'csp.middleware.CSPMiddleware',  # Content Security Policy
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
    #'default': {
     #   'ENGINE': 'django.db.backends.sqlite3',
      #  'NAME': BASE_DIR / 'db.sqlite3',
    #}
#}
# Usar PostgreSQL en producción, SQLite en desarrollo

if config('DATABASE_URL', default=None):

    # Producción: PostgreSQL desde Render

    import dj_database_url

    DATABASES = {

        'default': dj_database_url.config(

            default=config('DATABASE_URL'),

            conn_max_age=600,

            conn_health_checks=True,

        )

    }

else:

    # Desarrollo: SQLite

    DATABASES = {

        'default': {

            'ENGINE': 'django.db.backends.sqlite3',

            'NAME': BASE_DIR / 'db.sqlite3',

        }

    }


# Password validation - Configuración movida al final del archivo (línea 300)


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

 

# WhiteNoise para servir archivos estáticos en producción

if not DEBUG:

    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.Usuario'

# Configuración de Email (usando variables de entorno)
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 465
#EMAIL_USE_SSL = True
#EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='joadanvidal@gmail.com')
#EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='pkpukuqtvxbqqkvf')
#DEFAULT_FROM_EMAIL = EMAIL_HOST_USER# Configuración de Email con Resend

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.resend.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'resend'  # Literal "resend", no cambiar
EMAIL_HOST_PASSWORD = config('RESEND_API_KEY', default='')  # Tu API Key de Resend
DEFAULT_FROM_EMAIL = 'onboarding@resend.dev'  # Email por defecto de Resend (gratis)

# Configuración de SendGrid para OTP
SENDGRID_API_KEY = config('SENDGRID_API_KEY', default='')
SENDGRID_FROM_EMAIL = config('SENDGRID_FROM_EMAIL', default='')
SENDGRID_FROM_NAME = config('SENDGRID_FROM_NAME', default='modulo usuario')

# Configuración CORS para Angular Frontend y Vercel
# Obtener URL del frontend desde variables de entorno
FRONTEND_URL = config('FRONTEND_URL', default='https://frontbina.vercel.app')

# Lista de orígenes permitidos (orígenes específicos)
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='https://frontbina.vercel.app,http://localhost:4200,http://127.0.0.1:4200',
    cast=Csv()
)

# Permitir todos los subdominios de Vercel (para preview deployments)
# IMPORTANTE: El regex debe ser una lista de strings (patrones regex)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",  # Permite cualquier subdominio de Vercel
]

# Función personalizada para verificar orígenes (fallback si regex no funciona)
def cors_allow_origin(origin, request):
    """Función personalizada para permitir orígenes de Vercel"""
    if origin:
        # Permitir cualquier subdominio de vercel.app
        if origin.endswith('.vercel.app'):
            return True
        # Permitir localhost para desarrollo
        if origin.startswith('http://localhost:') or origin.startswith('http://127.0.0.1:'):
            return True
    return None  # Dejar que django-cors-headers maneje el resto con CORS_ALLOWED_ORIGINS

# Usar función personalizada como fallback si el regex no funciona
# Esta función tiene prioridad sobre CORS_ALLOWED_ORIGINS y CORS_ALLOWED_ORIGIN_REGEXES
CORS_ALLOW_ORIGIN_FUNC = cors_allow_origin

CORS_ALLOW_CREDENTIALS = True  # Para permitir cookies/sesiones

# Configuración adicional para asegurar que CORS funcione
CORS_PREFLIGHT_MAX_AGE = 86400  # Cache preflight requests por 24 horas

# Headers permitidos
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Métodos permitidos
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
# CSRF Settings para Angular y Vercel
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='https://frontbina.vercel.app,http://localhost:4200,http://127.0.0.1:4200',
    cast=Csv()
)

# Session Settings
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not DEBUG  # True en producción
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 86400  # 24 horas

# CSRF Cookie Settings
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG

CSRF_COOKIE_HTTPONLY = False  # Angular necesita leer el token

# ==================== CONFIGURACIONES DE SEGURIDAD ====================

# Password Hashers - Usar Argon2 (más seguro que PBKDF2)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

# Password Validation - Políticas de contraseña robustas
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==================== SEGURIDAD HTTP ====================

# HSTS (HTTP Strict Transport Security)
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 año en producción
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

# Otras cabeceras de seguridad
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_SSL_REDIRECT = not DEBUG  # Forzar HTTPS en producción

# Cookies seguras
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG

# Prevenir clickjacking
X_FRAME_OPTIONS = 'SAMEORIGIN'

# ==================== CONTENT SECURITY POLICY ====================

CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'", "https://accounts.google.com", "https://www.gstatic.com")
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com")
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com")
CSP_IMG_SRC = ("'self'", "data:", "https:")
CSP_CONNECT_SRC = ("'self'", "https://backendbina-1.onrender.com", "https://accounts.google.com")
CSP_FRAME_SRC = ("https://accounts.google.com",)

# ==================== DJANGO AXES - PROTECCIÓN FUERZA BRUTA ====================

# Backend de autenticación - Django Axes debe estar primero
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # Django Axes
    'django.contrib.auth.backends.ModelBackend',  # Backend por defecto de Django
]

# Configuración de Django Axes
AXES_FAILURE_LIMIT = 5  # Número de intentos fallidos antes de bloquear
AXES_COOLOFF_TIME = 1  # Tiempo de bloqueo en horas
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True  # Bloquear por combinación usuario + IP
AXES_RESET_ON_SUCCESS = True  # Resetear intentos al login exitoso
AXES_LOCKOUT_TEMPLATE = None  # Usar respuesta JSON en lugar de template
AXES_LOCKOUT_PARAMETERS = [["username", "email"]]  # Parámetros para trackear
AXES_IPWARE_PROXY_COUNT = 1  # Considerar proxies para obtener IP real
AXES_IPWARE_META_PRECEDENCE_ORDER = [
    'HTTP_X_FORWARDED_FOR',
    'X_FORWARDED_FOR',
    'HTTP_CLIENT_IP',
    'HTTP_X_REAL_IP',
    'HTTP_X_FORWARDED',
    'HTTP_X_CLUSTER_CLIENT_IP',
    'HTTP_FORWARDED_FOR',
    'HTTP_FORWARDED',
    'HTTP_VIA',
    'REMOTE_ADDR',
]

# ==================== SESIONES ====================

# Expiración de sesión por inactividad (15 minutos)
SESSION_COOKIE_AGE = 900  # 15 minutos
SESSION_SAVE_EVERY_REQUEST = True  # Actualizar cookie en cada request
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# ==================== LOGGING DE SEGURIDAD ====================

# Crear directorio de logs si no existe
import os
LOGS_DIR = BASE_DIR / 'logs'
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 1024 * 1024 * 15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'security.log',
            'maxBytes': 1024 * 1024 * 15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'axes_handler': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'axes.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'security': {
            'handlers': ['console', 'security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'axes': {
            'handlers': ['console', 'axes_handler'],
            'level': 'WARNING',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console', 'file', 'security_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ==================== DJANGO REST FRAMEWORK ====================

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}

# ==================== RATE LIMITING ====================

# Configuración para django-ratelimit
RATELIMIT_ENABLE = not DEBUG  # Activar solo en producción
RATELIMIT_USE_CACHE = 'default'

# Cache para rate limiting (usar memoria en desarrollo, Redis en producción)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# ==================== VALIDACIÓN DE CONFIGURACIÓN ====================

# Verificar configuración crítica en producción
if not DEBUG:
    assert not SECRET_KEY.startswith('django-dev'), "SECRET_KEY no configurada para producción"
    assert ALLOWED_HOSTS, "ALLOWED_HOSTS no configurado para producción"
    assert SECURE_SSL_REDIRECT, "HTTPS no está forzado en producción"
    assert SESSION_COOKIE_SECURE, "SESSION_COOKIE_SECURE debe ser True en producción"
    assert CSRF_COOKIE_SECURE, "CSRF_COOKIE_SECURE debe ser True en producción"
