"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-p&f859sfsdb#et935ty(dwxij=$6y$8_yv-l=nqi&$&)(smms_')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,frontbina.vercel.app', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # Para Angular frontend
    # Documentación API (descomentar después de instalar: pip install drf-yasg)
    # 'drf_yasg',  # Descomentar para habilitar documentación Swagger/ReDoc
    'accounts',
    'citas',
    'productos',
    'pagos',
    'barberos',
    'configuracion',
    'notificaciones',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Para archivos estáticos en producción
    'corsheaders.middleware.CorsMiddleware',  # Debe ir temprano
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.UsuarioAutenticadoMiddleware',  # Middleware personalizado
    # Rate limiting: habilitar solo en producción
    # 'core.middleware_rate_limit.RateLimitMiddleware',  # Descomentar en producción
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Habilitar rate limiting en producción si está configurado
ENABLE_RATE_LIMIT = config('ENABLE_RATE_LIMIT', default=False, cast=bool)
if ENABLE_RATE_LIMIT:
    MIDDLEWARE.insert(-2, 'core.middleware_rate_limit.RateLimitMiddleware')

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
    #'default': {
     #   'ENGINE': 'django.db.backends.sqlite3',
      #  'NAME': BASE_DIR / 'db.sqlite3',
    #}
#}
# Usar PostgreSQL en producción, SQLite en desarrollo

if config('DATABASE_URL', default=None):

    # Producción: PostgreSQL desde Render

    import dj_database_url

    DATABASES = {

        'default': dj_database_url.config(

            default=config('DATABASE_URL'),

            conn_max_age=600,

            conn_health_checks=True,

        )

    }

else:

    # Desarrollo: SQLite local

    DATABASES = {

        'default': {

            'ENGINE': 'django.db.backends.sqlite3',

            'NAME': BASE_DIR / 'db.sqlite3',

        }

    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

 

# WhiteNoise para servir archivos estáticos en producción

if not DEBUG:

    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.Usuario'

# Configuración de Email (usando variables de entorno)
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 465
#EMAIL_USE_SSL = True
#EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='joadanvidal@gmail.com')
#EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='pkpukuqtvxbqqkvf')
#DEFAULT_FROM_EMAIL = EMAIL_HOST_USER# Configuración de Email con Resend

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.resend.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'resend'  # Literal "resend", no cambiar
EMAIL_HOST_PASSWORD = config('RESEND_API_KEY', default='')  # Tu API Key de Resend
DEFAULT_FROM_EMAIL = 'onboarding@resend.dev'  # Email por defecto de Resend (gratis)

# Configuración CORS para Angular Frontend
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:4200,http://127.0.0.1:4200,https://frontbina.vercel.app',
    cast=Csv()
)
CORS_ALLOW_CREDENTIALS = True  # Para permitir cookies/sesiones
# Headers adicionales de CORS
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
# CSRF Settings para Angular
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost:4200,http://127.0.0.1:4200,https://frontbina.vercel.app',
    cast=Csv()
)

# Session Settings
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not DEBUG  # True en producción
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 86400  # 24 horas

# CSRF Cookie Settings
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG

CSRF_COOKIE_HTTPONLY = False  # Angular necesita leer el token


# ============================================
# CONFIGURACIÓN DE PAGOS
# ============================================

# Mercado Pago
MERCADO_PAGO_ACCESS_TOKEN = config('MERCADO_PAGO_ACCESS_TOKEN', default='')
MERCADO_PAGO_SUCCESS_URL = config('MERCADO_PAGO_SUCCESS_URL', default='http://localhost:4200/pago-exitoso')
MERCADO_PAGO_FAILURE_URL = config('MERCADO_PAGO_FAILURE_URL', default='http://localhost:4200/pago-fallido')
MERCADO_PAGO_PENDING_URL = config('MERCADO_PAGO_PENDING_URL', default='http://localhost:4200/pago-pendiente')

# NOTA: La integración bancaria específica está pendiente
# hasta que se defina qué banco utilizará el negocio para recibir transferencias


# ============================================
# CONFIGURACIÓN DE NOTIFICACIONES
# ============================================

# Firebase Cloud Messaging (Push Notifications)
# Habilitar con FCM_ENABLED=True en variables de entorno
# Requiere archivo: config/firebase-service-account.json
FCM_ENABLED = config('FCM_ENABLED', default=False, cast=bool)

# Twilio (SMS) - Pendiente implementación
# TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
# TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
# TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER', default='')


# ============================================
# CONFIGURACIÓN DE CACHE
# ============================================

# Cache: Redis en producción, local en desarrollo
REDIS_URL = config('REDIS_URL', default=None)

if REDIS_URL:
    # Producción: Redis
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }
else:
    # Desarrollo: Cache local
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }

# Tiempo de cache por defecto (en segundos)
CACHE_TTL = config('CACHE_TTL', default=300, cast=int)  # 5 minutos por defecto




