# Generated by Django 5.2 on 2026-01-28 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('especialidades', models.TextField(blank=True, help_text='Especialidades del barbero')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_barbero', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Barbero',
                'verbose_name_plural': 'Barberos',
                'ordering': ['usuario__first_name', 'usuario__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ServicioBarbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_minutos', models.IntegerField(help_text='Tiempo estimado que tarda este barbero en realizar el servicio')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='barberos.barbero')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.servicio')),
            ],
            options={
                'verbose_name': 'Servicio de Barbero',
                'verbose_name_plural': 'Servicios de Barberos',
                'ordering': ['barbero', 'servicio'],
                'unique_together': {('barbero', 'servicio')},
            },
        ),
    ]
