# Generated by Django 5.2 on 2026-01-28 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_minutos', models.IntegerField(default=30, help_text='Duración estimada en minutos')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.CharField(choices=[('corte', 'Corte de Cabello'), ('barba', 'Arreglo de Barba'), ('combo', 'Combo (Corte + Barba)'), ('tratamiento', 'Tratamiento'), ('tinte', 'Tinte')], default='corte', max_length=50)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Silla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número de la silla (Silla 1, Silla 2, etc.)', unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo (ej: Silla 1)', max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Silla',
                'verbose_name_plural': 'Sillas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('duracion_minutos', models.IntegerField(help_text='Duración real de la cita')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], default='pendiente', max_length=20)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anticipo_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('anticipo_requerido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago_anticipo', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago')], max_length=20)),
                ('metodo_pago_restante', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_asistencia', models.DateTimeField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la cita')),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('barbero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_barbero', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_cliente', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(help_text='Usuario que registró la cita (secretaria o cliente)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_registradas', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citas.servicio')),
                ('silla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='citas.silla')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['fecha_hora', 'estado'], name='citas_cita_fecha_h_e91b0d_idx'), models.Index(fields=['cliente', 'estado'], name='citas_cita_cliente_e67168_idx'), models.Index(fields=['barbero', 'fecha_hora'], name='citas_cita_barbero_5d9802_idx')],
            },
        ),
    ]
