# Generated by Django 5.2 on 2026-01-28 16:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('categoria', models.CharField(choices=[('cera', 'Cera para Cabello'), ('shampoo', 'Shampoo'), ('acondicionador', 'Acondicionador'), ('pomada', 'Pomada'), ('aceite_barba', 'Aceite para Barba'), ('tratamiento', 'Tratamiento Capilar'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('stock_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.IntegerField(default=5, help_text='Stock mínimo antes de alertar')),
                ('imagen_url', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria', 'nombre'],
                'indexes': [models.Index(fields=['categoria', 'activo'], name='productos_p_categor_424163_idx'), models.Index(fields=['stock_actual'], name='productos_p_stock_a_1e27bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_entrega', models.CharField(choices=[('local', 'Recoger en Local'), ('moto_mandado', 'Moto Mandado Regional'), ('paqueteria', 'Paquetería Nacional')], default='local', max_length=20)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('direccion_entrega', models.TextField(blank=True, help_text='Dirección si es envío')),
                ('estado', models.CharField(choices=[('apartado', 'Apartado'), ('pagado', 'Pagado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='apartado', max_length=20)),
                ('pagado', models.BooleanField(default=False)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago')], max_length=20)),
                ('id_pago_transferencia', models.CharField(blank=True, help_text='ID de operación bancaria', max_length=100)),
                ('pago_validado', models.BooleanField(default=False, help_text='Validado por secretaria')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(help_text='Usuario que registró la compra (secretaria o cliente)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_registradas', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['cliente', 'estado'], name='productos_c_cliente_d2406f_idx'), models.Index(fields=['estado', 'pagado'], name='productos_c_estado_65c977_idx')],
            },
        ),
    ]
