# Generated by Django 5.2 on 2026-01-28 18:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_entrega', models.CharField(choices=[('local', 'Recoger en Local'), ('moto_mandado', 'Moto Mandado Regional'), ('paqueteria', 'Paquetería Nacional')], default='local', max_length=20)),
                ('direccion_entrega', models.TextField(blank=True, help_text='Dirección si es envío')),
                ('estado', models.CharField(choices=[('apartado', 'Apartado'), ('pagado', 'Pagado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='apartado', max_length=20)),
                ('pagado', models.BooleanField(default=False)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mercado_pago', 'Mercado Pago')], max_length=20)),
                ('id_pago_transferencia', models.CharField(blank=True, help_text='ID de operación bancaria', max_length=100)),
                ('pago_validado', models.BooleanField(default=False, help_text='Validado por secretaria')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(help_text='Usuario que registró la compra (secretaria o cliente)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productos.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Item de orden',
                'verbose_name_plural': 'Items de orden',
            },
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['cliente', 'estado'], name='productos_o_cliente_e794fb_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['estado', 'pagado'], name='productos_o_estado_c9245e_idx'),
        ),
    ]
